# Generated by Django 4.2.7 on 2023-11-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('soyad', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
            ],
        ),
    ]
