# Generated by Django 4.2.7 on 2023-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_userreg_mail_alter_userreg_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
