# Generated by Django 4.2.7 on 2023-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Dat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_time', models.TimeField(max_length=255)),
                ('exam_quescount', models.BigIntegerField()),
                ('exam_grade', models.SmallIntegerField()),
                ('questions', models.CharField(max_length=255)),
            ],
        ),
    ]
