# Generated by Django 4.2.7 on 2023-11-07 07:59

from django.db import migrations, models

TYPE_CHOICES =(
("noun","The Noun"),
("pronoun","Pronoun"),
("article","Article"),
("sodoi","So do I"),
("quantifiers","Quantifiers"),
("tenses","Tense Forms"),
("passive","Passive Voice"),
("modal","Modal Verbs"),
)

class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_exam_dat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_topic', models.CharField(choices=TYPE_CHOICES,max_length=30)),
                ('question_c1', models.TextField()),
                ('question_c2', models.TextField()),
                ('question_c3', models.TextField()),
                ('question_c4', models.TextField()),
                ('question_c5', models.TextField()),
                ('correct_ans', models.TextField()),
                ('question_id', models.CharField(max_length=255)),
            ],
        ),
    ]
