# Generated by Django 4.2.7 on 2023-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_grammar_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar_bank',
            name='question_topic',
            field=models.CharField(choices=[(1, 'The Noun'), (2, 'Pronoun'), (3, 'Article'), (4, 'So do I'), (5, 'Quantifiers'), (6, 'Tense Forms'), (7, 'Passive Voice'), (8, 'Modal Verbs')], max_length=40),
        ),
    ]
