# Generated by Django 4.2.7 on 2023-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_grammar_bank_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar_bank',
            name='question_topic',
            field=models.CharField(choices=[('noun', 'The Noun'), ('pronoun', 'Pronoun'), ('article', 'Article'), ('sodoi', 'So do I'), ('quantifiers', 'Quantifiers'), ('tenses', 'Tense Forms'), ('passive', 'Passive Voice'), ('modal', 'Modal Verbs')], max_length=40),
        ),
    ]
