# Generated by Django 4.2.7 on 2023-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_grammar_bank_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar_bank',
            name='question_type',
            field=models.CharField(choices=[('open', 'Açıq'), ('close', 'Qapalı')], default='close', max_length=40),
        ),
    ]
