# Generated by Django 4.2.7 on 2023-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_grammar_bank_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_dat',
            name='participated_childrens',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
