# Generated by Django 4.2.7 on 2023-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_exam_dat_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_dat',
            name='exam_end',
            field=models.DateTimeField(default='2023-11-11 16:00:00', max_length=255),
        ),
    ]
