# Generated by Django 4.2.7 on 2023-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_exam_dat_exam_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_dat',
            name='exam_end',
            field=models.DateTimeField(max_length=255),
        ),
    ]
